'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.4.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("localhost\SQLEXPRESS")>  _
        Public Property FailureReportDataBaseDataSource() As String
            Get
                Return CType(Me("FailureReportDataBaseDataSource"),String)
            End Get
            Set
                Me("FailureReportDataBaseDataSource") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TRUE")>  _
        Public Property FailureReportDBIntegratedSecurityState() As String
            Get
                Return CType(Me("FailureReportDBIntegratedSecurityState"),String)
            End Get
            Set
                Me("FailureReportDBIntegratedSecurityState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FAILURE_REPORT")>  _
        Public Property FailureReportDataInitialCatalog() As String
            Get
                Return CType(Me("FailureReportDataInitialCatalog"),String)
            End Get
            Set
                Me("FailureReportDataInitialCatalog") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\SQLEXPRESS;Initial Catalog=FAILURE_REPORT;Integrated Securi"& _ 
            "ty=True")>  _
        Public Property FailureReportDataBaseFullConnectionString() As String
            Get
                Return CType(Me("FailureReportDataBaseFullConnectionString"),String)
            End Get
            Set
                Me("FailureReportDataBaseFullConnectionString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\SQLEXPRESS;Initial Catalog=METER_SPECS;Integrated Security="& _ 
            "True")>  _
        Public Property MeterSpecDataBaseFullConnectionString() As String
            Get
                Return CType(Me("MeterSpecDataBaseFullConnectionString"),String)
            End Get
            Set
                Me("MeterSpecDataBaseFullConnectionString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("METER_SPECS")>  _
        Public Property MeterSpecDataBaseInitialCatalog() As String
            Get
                Return CType(Me("MeterSpecDataBaseInitialCatalog"),String)
            End Get
            Set
                Me("MeterSpecDataBaseInitialCatalog") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("localhost\SQLEXPRESS")>  _
        Public Property MeterSpecDataBaseDataSource() As String
            Get
                Return CType(Me("MeterSpecDataBaseDataSource"),String)
            End Get
            Set
                Me("MeterSpecDataBaseDataSource") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("true")>  _
        Public Property MeterSpecDBIntegratedSecurityState() As String
            Get
                Return CType(Me("MeterSpecDBIntegratedSecurityState"),String)
            End Get
            Set
                Me("MeterSpecDBIntegratedSecurityState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Admin")>  _
        Public Property MyUserName() As String
            Get
                Return CType(Me("MyUserName"),String)
            End Get
            Set
                Me("MyUserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\Uslafvs001038\hqa\Software\Failure Report Database\Attachments")>  _
        Public Property AttachmentFolder() As String
            Get
                Return CType(Me("AttachmentFolder"),String)
            End Get
            Set
                Me("AttachmentFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Index,False;Original ID,False;Anomaly,False;Failure Description,False;Corrective "& _ 
            "Action,False;Engineering Notes,False;TCC Comments,False")>  _
        Public Property GridViewColumnStates() As String
            Get
                Return CType(Me("GridViewColumnStates"),String)
            End Get
            Set
                Me("GridViewColumnStates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DGVPrintSettings() As String
            Get
                Return CType(Me("DGVPrintSettings"),String)
            End Get
            Set
                Me("DGVPrintSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DGVPageSettings() As String
            Get
                Return CType(Me("DGVPageSettings"),String)
            End Get
            Set
                Me("DGVPageSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Prompt_To_Change_Database() As Boolean
            Get
                Return CType(Me("Prompt_To_Change_Database"),Boolean)
            End Get
            Set
                Me("Prompt_To_Change_Database") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Password() As String
            Get
                Return CType(Me("Password"),String)
            End Get
            Set
                Me("Password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RecentFolder() As String
            Get
                Return CType(Me("RecentFolder"),String)
            End Get
            Set
                Me("RecentFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\SQLEXPRESS;Initial Catalog=FAILURE_REPORT;Integrated Securi"& _ 
            "ty=True")>  _
        Public ReadOnly Property FAILURE_REPORTConnectionString() As String
            Get
                Return CType(Me("FAILURE_REPORTConnectionString"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.FailureReportDatabase.My.MySettings
            Get
                Return Global.FailureReportDatabase.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
